// <auto-generated />
using System;
using AgileExam.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(CardContext))]
    [Migration("20240527200521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("AgileExam.Models.BirthdayCard", b =>
                {
                    b.Property<int>("BirthdayCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BirthdayCardId");

                    b.HasIndex("UserId");

                    b.ToTable("BirthdayCards");
                });

            modelBuilder.Entity("AgileExam.Models.History", b =>
                {
                    b.Property<int?>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("QueueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("HistoryId");

                    b.HasIndex("QueueId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("AgileExam.Models.MediaCard", b =>
                {
                    b.Property<int>("MediaCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MediaCardId");

                    b.HasIndex("UserId");

                    b.ToTable("MediaCards");
                });

            modelBuilder.Entity("AgileExam.Models.Queue", b =>
                {
                    b.Property<int?>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BirthdayCardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaCardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("QueueId");

                    b.HasIndex("BirthdayCardId")
                        .IsUnique();

                    b.HasIndex("MediaCardId")
                        .IsUnique();

                    b.ToTable("Queue");
                });

            modelBuilder.Entity("AgileExam.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AgileExam.Models.BirthdayCard", b =>
                {
                    b.HasOne("AgileExam.Models.User", "User")
                        .WithMany("BirthdayCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgileExam.Models.History", b =>
                {
                    b.HasOne("AgileExam.Models.Queue", "Queue")
                        .WithMany("Histories")
                        .HasForeignKey("QueueId");

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("AgileExam.Models.MediaCard", b =>
                {
                    b.HasOne("AgileExam.Models.User", "User")
                        .WithMany("MediaCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AgileExam.Models.Queue", b =>
                {
                    b.HasOne("AgileExam.Models.BirthdayCard", "BirthdayCard")
                        .WithOne()
                        .HasForeignKey("AgileExam.Models.Queue", "BirthdayCardId");

                    b.HasOne("AgileExam.Models.MediaCard", "MediaCard")
                        .WithOne()
                        .HasForeignKey("AgileExam.Models.Queue", "MediaCardId");

                    b.Navigation("BirthdayCard");

                    b.Navigation("MediaCard");
                });

            modelBuilder.Entity("AgileExam.Models.Queue", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("AgileExam.Models.User", b =>
                {
                    b.Navigation("BirthdayCards");

                    b.Navigation("MediaCards");
                });
#pragma warning restore 612, 618
        }
    }
}
